interface FontOption {
  name: string;
  cssName: string;
}

export const FONT_LIST: FontOption[] = [
  // Originals
  { name: 'Roboto', cssName: "'Roboto', sans-serif" },
  { name: 'Lato', cssName: "'Lato', sans-serif" },
  { name: 'Merriweather', cssName: "'Merriweather', serif" },
  { name: 'Lobster', cssName: "'Lobster', cursive" },
  { name: 'Noto Nastaliq Urdu', cssName: "'Noto Nastaliq Urdu', serif" },
  // Sans-Serif
  { name: 'Open Sans', cssName: "'Open Sans', sans-serif" },
  { name: 'Montserrat', cssName: "'Montserrat', sans-serif" },
  { name: 'Source Sans Pro', cssName: "'Source Sans Pro', sans-serif" },
  { name: 'Oswald', cssName: "'Oswald', sans-serif" },
  { name: 'Raleway', cssName: "'Raleway', sans-serif" },
  { name: 'Poppins', cssName: "'Poppins', sans-serif" },
  { name: 'Nunito', cssName: "'Nunito', sans-serif" },
  { name: 'Ubuntu', cssName: "'Ubuntu', sans-serif" },
  { name: 'Arimo', cssName: "'Arimo', sans-serif" },
  { name: 'Fira Sans', cssName: "'Fira Sans', sans-serif" },
  { name: 'Quicksand', cssName: "'Quicksand', sans-serif" },
  { name: 'Work Sans', cssName: "'Work Sans', sans-serif" },
  { name: 'Dosis', cssName: "'Dosis', sans-serif" },
  { name: 'Cabin', cssName: "'Cabin', sans-serif" },
  { name: 'Josefin Sans', cssName: "'Josefin Sans', sans-serif" },
  { name: 'Anton', cssName: "'Anton', sans-serif" },
  { name: 'Exo 2', cssName: "'Exo 2', sans-serif" },
  { name: 'Muli', cssName: "'Muli', sans-serif" },
  { name: 'Hind', cssName: "'Hind', sans-serif" },
  // Serif
  { name: 'Playfair Display', cssName: "'Playfair Display', serif" },
  { name: 'Lora', cssName: "'Lora', serif" },
  { name: 'PT Serif', cssName: "'PT Serif', serif" },
  { name: 'Slabo 27px', cssName: "'Slabo 27px', serif" },
  { name: 'Cormorant Garamond', cssName: "'Cormorant Garamond', serif" },
  { name: 'Bitter', cssName: "'Bitter', serif" },
  { name: 'Crimson Text', cssName: "'Crimson Text', serif" },
  { name: 'Vollkorn', cssName: "'Vollkorn', serif" },
  { name: 'Arvo', cssName: "'Arvo', serif" },
  { name: 'Zilla Slab', cssName: "'Zilla Slab', serif" },
  { name: 'Cardo', cssName: "'Cardo', serif" },
  { name: 'Domine', cssName: "'Domine', serif" },
  { name: 'Old Standard TT', cssName: "'Old Standard TT', serif" },
  // Display
  { name: 'Bebas Neue', cssName: "'Bebas Neue', cursive" },
  { name: 'Righteous', cssName: "'Righteous', cursive" },
  { name: 'Comfortaa', cssName: "'Comfortaa', cursive" },
  { name: 'Abril Fatface', cssName: "'Abril Fatface', cursive" },
  { name: 'Fredoka One', cssName: "'Fredoka One', cursive" },
  { name: 'Alfa Slab One', cssName: "'Alfa Slab One', cursive" },
  { name: 'Patua One', cssName: "'Patua One', cursive" },
  { name: 'Passion One', cssName: "'Passion One', cursive" },
  { name: 'Sigmar One', cssName: "'Sigmar One', cursive" },
  { name: 'Bungee', cssName: "'Bungee', cursive" },
  { name: 'Press Start 2P', cssName: "'Press Start 2P', cursive" },
  { name: 'Monoton', cssName: "'Monoton', cursive" },
  { name: 'Ultra', cssName: "'Ultra', serif" },
  { name: 'Graduate', cssName: "'Graduate', cursive" },
  { name: 'Shrikhand', cssName: "'Shrikhand', cursive" },
  // Handwriting
  { name: 'Dancing Script', cssName: "'Dancing Script', cursive" },
  { name: 'Pacifico', cssName: "'Pacifico', cursive" },
  { name: 'Caveat', cssName: "'Caveat', cursive" },
  { name: 'Indie Flower', cssName: "'Indie Flower', cursive" },
  { name: 'Shadows Into Light', cssName: "'Shadows Into Light', cursive" },
  { name: 'Amatic SC', cssName: "'Amatic SC', cursive" },
  { name: 'Permanent Marker', cssName: "'Permanent Marker', cursive" },
  { name: 'Great Vibes', cssName: "'Great Vibes', cursive" },
  { name: 'Sacramento', cssName: "'Sacramento', cursive" },
  { name: 'Gochi Hand', cssName: "'Gochi Hand', cursive" },
  { name: 'Architects Daughter', cssName: "'Architects Daughter', cursive" },
  { name: 'Patrick Hand', cssName: "'Patrick Hand', cursive" },
  { name: 'Kalam', cssName: "'Kalam', cursive" },
  { name: 'Handlee', cssName: "'Handlee', cursive" },
  { name: 'Just Me Again Down Here', cssName: "'Just Me Again Down Here', cursive" },
  // Monospace
  { name: 'Source Code Pro', cssName: "'Source Code Pro', monospace" },
  { name: 'Inconsolata', cssName: "'Inconsolata', monospace" },
  { name: 'Roboto Mono', cssName: "'Roboto Mono', monospace" },
  { name: 'Space Mono', cssName: "'Space Mono', monospace" },
  { name: 'Cutive Mono', cssName: "'Cutive Mono', monospace" },
  { name: 'Nanum Gothic Coding', cssName: "'Nanum Gothic Coding', monospace" },
  { name: 'Fira Mono', cssName: "'Fira Mono', monospace" },
  { name: 'Share Tech Mono', cssName: "'Share Tech Mono', monospace" },
  { name: 'Anonymous Pro', cssName: "'Anonymous Pro', monospace" },
  { name: 'Cousine', cssName: "'Cousine', monospace" },
  { name: 'VT323', cssName: "'VT323', monospace" },
  // Additional interesting fonts
  { name: 'Teko', cssName: "'Teko', sans-serif" },
  { name: 'Yanone Kaffeesatz', cssName: "'Yanone Kaffeesatz', sans-serif" },
  { name: 'Kanit', cssName: "'Kanit', sans-serif" },
  { name: 'Prompt', cssName: "'Prompt', sans-serif" },
  { name: 'Cinzel', cssName: "'Cinzel', serif" },
  { name: 'Fauna One', cssName: "'Fauna One', serif" },
  { name: 'Philosopher', cssName: "'Philosopher', sans-serif" },
  { name: 'Orbitron', cssName: "'Orbitron', sans-serif" },
  { name: 'Audiowide', cssName: "'Audiowide', cursive" },
  { name: 'Syncopate', cssName: "'Syncopate', sans-serif" },
  { name: 'Gruppo', cssName: "'Gruppo', sans-serif" },
  { name: 'Megrim', cssName: "'Megrim', cursive" },
  { name: 'Uncial Antiqua', cssName: "'Uncial Antiqua', cursive" },
  { name: 'IM Fell English SC', cssName: "'IM Fell English SC', serif" },
  { name: 'Special Elite', cssName: "'Special Elite', cursive" },
  { name: 'Homemade Apple', cssName: "'Homemade Apple', cursive" },
  { name: 'Rock Salt', cssName: "'Rock Salt', cursive" },
  { name: 'Fredericka the Great', cssName: "'Fredericka the Great', cursive" },
  { name: 'Bangers', cssName: "'Bangers', cursive" },
  { name: 'Luckiest Guy', cssName: "'Luckiest Guy', cursive" },
  { name: 'Creepster', cssName: "'Creepster', cursive" },
  { name: 'Nosifier', cssName: "'Nosifier', cursive" },
  { name: 'Codystar', cssName: "'Codystar', cursive" },
  { name: 'Eater', cssName: "'Eater', cursive" },
  { name: 'Metal Mania', cssName: "'Metal Mania', cursive" },
  { name: 'Faster One', cssName: "'Faster One', cursive" },
];
